-- ========================================================================
-- ⚠️ Exécuter chaque étape individuellement selon les instructions du TP
-- ⚠️ Ne pas exécuter ce script en entièreté
-- ========================================================================

-- =========
-- 🧩 Étape 2
-- =========
-- ===========================
-- Création des tables
-- ===========================
create table patients_jad (
   patient_id     number(6) primary key,
   nom            varchar2(30) not null,
   prenom         varchar2(30) not null,
   sexe           char(1) check ( sexe in ( 'M',
                                  'F' ) ) not null
);
create table medecins_jad (
   medecin_id number(6) primary key,
   nom        varchar2(30) not null,
   specialite varchar2(50),
   email      varchar2(100) unique
);
create table consultations_jad (
   consultation_id   number(6) primary key,
   patient_id        number(6),
   medecin_id        number(6),
   date_consultation date default sysdate,
   constraint fk_patient foreign key ( patient_id )
      references patients_jad ( patient_id )
         on delete cascade,
   constraint fk_medecin foreign key ( medecin_id )
      references medecins_jad ( medecin_id )
         on delete cascade
);
-- Tables encryptées
create table crypto_infos_jad (
   patient_id           number primary key,
   date_naissance       raw(256),
   adresse              raw(256),
   num_secu             raw(256),
   diagnostic           raw(256),
   traitement           raw(256),
   rapport_consultation raw(256),
   cout_consultation    raw(256)
);

create table crypto_cles_jad (
   patient_id  number primary key,
   cle_cryptee         raw(256) not null
);
create table record_retour (
   patient_id           number primary key,
   date_naissance       date,
   adresse              varchar2(100),
   num_secu             varchar2(20),
   diagnostic           varchar2(2000),
   traitement           varchar2(2000),
   rapport_consultation varchar2(2000),
   cout_consultation    number
);

-- ===========================
-- Peuplement des tables
-- ===========================
insert into patients_jad (
   patient_id,
   nom,
   prenom,
   sexe
) values ( 101,
           'Dupont',
           'Marie',
           'F' );
insert into patients_jad (
   patient_id,
   nom,
   prenom,
   sexe
) values ( 102,
           'Nguyen',
           'Alex',
           'M' );
insert into patients_jad (
   patient_id,
   nom,
   prenom,
   sexe
) values ( 103,
           'Smith',
           'Emma',
           'F' );
insert into patients_jad (
   patient_id,
   nom,
   prenom,
   sexe
) values ( 104,
           'Benali',
           'Karim',
           'M' );
insert into medecins_jad (
   medecin_id,
   nom,
   specialite,
   email
) values ( 201,
           'Tremblay',
           'Généraliste',
           'tremblay.medecin@hopital.ca' );
insert into medecins_jad (
   medecin_id,
   nom,
   specialite,
   email
) values ( 202,
           'Gauthier',
           'Cardiologue',
           'gauthier.cardio@hopital.ca' );
insert into medecins_jad (
   medecin_id,
   nom,
   specialite,
   email
) values ( 203,
           'Lefebvre',
           'Endocrinologue',
           'lefebvre.endo@hopital.ca' );
insert into medecins_jad (
   medecin_id,
   nom,
   specialite,
   email
) values ( 204,
           'Dubois',
           'Allergologue',
           'dubois.allergie@hopital.ca' );
insert into consultations_jad (
   consultation_id,
   patient_id,
   medecin_id,
   date_consultation
) values ( 301,
           101,
           201,
           to_date('2025-10-01','YYYY-MM-DD') );
insert into consultations_jad (
   consultation_id,
   patient_id,
   medecin_id,
   date_consultation
) values ( 302,
           102,
           202,
           to_date('2025-10-05','YYYY-MM-DD') );
insert into consultations_jad (
   consultation_id,
   patient_id,
   medecin_id,
   date_consultation
) values ( 303,
           103,
           203,
           to_date('2025-10-10','YYYY-MM-DD') );
insert into consultations_jad (
   consultation_id,
   patient_id,
   medecin_id,
   date_consultation
) values ( 304,
           104,
           204,
           to_date('2025-10-20','YYYY-MM-DD') );

commit;

-- =========
-- 🧩 Étape 4
-- =========
-- Audits
create table audit_action_jad (
   audit_id    number generated by default as identity primary key,
   username    varchar2(30),
   action      varchar2(100),
   objet       varchar2(1000),
   date_action timestamp default systimestamp
);

-- Trigger d’audit sur la table Patients
create or replace trigger trigger_modif_patients_jad before
   insert or update or delete on patients_jad
   for each row
declare
   v_user varchar2(100);
begin
   v_user := sys_context(
      'userenv',
      'session_user'
   );
   if inserting then
      insert into audit_action_jad (
         username,
         action,
         objet,
         date_action
      ) values ( v_user,
                 'INSERT ',
                 'id : '
                 || :new.patient_id
                 || ', nom : '
                 || :new.nom
                 || ', prenom : '
                 || :new.prenom
                 || ', sexe : '
                 || :new.sexe,
                 current_timestamp );
elsif updating then
insert into audit_action_jad (
    username,
    action,
    objet,
    date_action
) values ( v_user,
'UPDATE ',
'id : '
|| :old.patient_id
|| ' -> '
|| :new.patient_id
|| ', nom : '
|| :old.nom
|| ' -> '
|| :new.nom
|| ', prenom : '
|| :old.prenom
|| ' -> '
|| :new.prenom
|| ', sexe : '
|| :old.sexe
|| ' -> '
|| :new.sexe,
current_timestamp );
elsif deleting then
insert into audit_action_jad (
    username,
    action,
    objet,
    date_action
) values ( v_user,
'DELETE ',
'id : '
|| :old.patient_id
|| ', nom : '
|| :old.nom
|| ', prenom  :'
|| :old.prenom
|| ', sexe : '
|| :old.sexe,
current_timestamp );
   end if;
end;
/
commit;
-- ============
-- 🧩 Étape 6
-- ============
-- Package de chiffrement
create or replace package crypto_jad is
   function encrypt_data (
      p_id                    in number,
      p_date_naissance        in date,
      p_adresse               in varchar2,
      p_num_secu              in varchar2,
      p_diagnostic            in varchar2,
      p_traitement            in varchar2,
      p_rapport_consultation  in varchar2,
      p_cout_consultation     in number,
      p_code                  in varchar2 default null
   ) return number;
   function decrypt_data (
      p_id   in number,
      p_code in varchar2 default null
   ) return record_retour%rowtype;
end crypto_jad;
/

create or replace package body crypto_jad is
   main_mdp_visible varchar2(7) := 'mainTP2';
   main_mdp raw(32) := dbms_crypto.hash(
         utl_i18n.string_to_raw(main_mdp_visible, 'AL32UTF8'),
         dbms_crypto.hash_sh256);
   free_mdp varchar2(7) := 'freeTP2';
   enc_mode number := dbms_crypto.encrypt_aes256 + dbms_crypto.chain_cbc + dbms_crypto.pad_pkcs5;
   
   -- =========================

   function encrypt_data (
      p_id                    in number,
      p_date_naissance        in date,
      p_adresse               in varchar2,
      p_num_secu              in varchar2,
      p_diagnostic            in varchar2,
      p_traitement            in varchar2,
      p_rapport_consultation  in varchar2,
      p_cout_consultation     in number,
      p_code                  in varchar2 default null
   ) return number is
      cle_visible   raw(256);
   begin
      if p_code is null
      or p_code != free_mdp then
         return null;
      end if;

      cle_visible := dbms_crypto.randombytes(32);
      
      insert into crypto_infos_jad values(
         p_id,
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(to_char(p_date_naissance, 'YYYY-MM-DD'), 'AL32UTF8'),
            enc_mode,
            cle_visible
         ),
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(p_adresse, 'AL32UTF8'),
            enc_mode,
            cle_visible
         ),
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(p_num_secu, 'AL32UTF8'),
            enc_mode,
            cle_visible
         ),
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(p_diagnostic, 'AL32UTF8'),
            enc_mode,
            cle_visible
         ),
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(p_traitement, 'AL32UTF8'),
            enc_mode,
            cle_visible
         ),
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(p_rapport_consultation, 'AL32UTF8'),
            enc_mode,
            cle_visible
         ),
         dbms_crypto.encrypt(
            utl_i18n.string_to_raw(to_char(p_cout_consultation), 'AL32UTF8'),
            enc_mode,
            cle_visible
         )
      );

      insert into crypto_cles_jad values(
         p_id,
         dbms_crypto.encrypt(
            cle_visible,
            enc_mode,
            main_mdp
         )
      );
      return p_id;
   end encrypt_data;

   function decrypt_data (
      p_id   in number,
      p_code in varchar2 default null
   ) return record_retour%rowtype is
   -- Record à retourner
      l_record                record_retour%rowtype;
   -- Clés à utiliser
      l_cle_cryptee           raw(256);
      l_cle_visible           raw(256);
   -- Informations du patient
      l_date_naissance        date;
      l_adresse               varchar2(100);
      l_num_secu              varchar2(20);
      l_diagnostic            varchar2(2000);
      l_traitement            varchar2(2000);

      l_rapport_consultation  varchar2(2000);
      l_cout_consultation     number;
   -- record crypté temporaire
      l_temp                  crypto_infos_jad%rowtype;
   begin
      if p_code is null
      or p_code != free_mdp then
         return null;
      end if;

      select cle_cryptee into l_cle_cryptee from crypto_cles_jad where patient_id = p_id;
      l_cle_visible := dbms_crypto.decrypt(
         l_cle_cryptee,
         enc_mode,
         main_mdp
      );

      select * into l_temp from crypto_infos_jad where patient_id = p_id;
      
      -- date_naissance
      l_date_naissance :=
      to_date(
         utl_i18n.raw_to_char(
            dbms_crypto.decrypt(l_temp.date_naissance, enc_mode, l_cle_visible),
            'AL32UTF8'
         ),
         'YYYY-MM-DD'
      );

      -- adresse
      l_adresse :=
      utl_i18n.raw_to_char(
         dbms_crypto.decrypt(l_temp.adresse, enc_mode, l_cle_visible),
         'AL32UTF8'
      );

      -- num_secu
      l_num_secu :=
      utl_i18n.raw_to_char(
         dbms_crypto.decrypt(l_temp.num_secu, enc_mode, l_cle_visible),
         'AL32UTF8'
      );

      -- diagnostic
      l_diagnostic :=
      utl_i18n.raw_to_char(
         dbms_crypto.decrypt(l_temp.diagnostic, enc_mode, l_cle_visible),
         'AL32UTF8'
      );

      -- traitement
      l_traitement :=
      utl_i18n.raw_to_char(
         dbms_crypto.decrypt(l_temp.traitement, enc_mode, l_cle_visible),
         'AL32UTF8'
      );

      -- rapport_consultation
      l_rapport_consultation :=
      utl_i18n.raw_to_char(
         dbms_crypto.decrypt(l_temp.rapport_consultation, enc_mode, l_cle_visible),
         'AL32UTF8'
      );
      
      -- cout_consultation
      l_cout_consultation :=
      to_number(
         utl_i18n.raw_to_char(
            dbms_crypto.decrypt(l_temp.cout_consultation, enc_mode, l_cle_visible),
            'AL32UTF8'
         )
      );
      
      l_record.patient_id            := p_id;
      l_record.date_naissance        := l_date_naissance;
      l_record.adresse               := l_adresse;
      l_record.num_secu              := l_num_secu;
      l_record.diagnostic            := l_diagnostic;
      l_record.traitement            := l_traitement;
      l_record.rapport_consultation  := l_rapport_consultation;
      l_record.cout_consultation     := l_cout_consultation;

      return l_record;
   end decrypt_data;
end crypto_jad;
/